executable              = /home/parkerw/Scripts/condor_pair_open.sh
universe                = vanilla
output                  = /home/parkerw/Scripts/condor_pair_open.log
error                   = /home/parkerw/Scripts/condor_pair_open.err
log                     = /home/parkerw/Scripts/condor_pair_open.out
notification            = never
priority                = 5
getenv                  = False
queue 1
