executable              = /home/parkerw/Scripts/savetree_6to14alph.sh
universe                = vanilla
output                  = /home/parkerw/Scripts/savetree6to14alph.log
error                   = /home/parkerw/Scripts/savetree6to14alph.err
log                     = /home/parkerw/Scripts/savetree6to14alph.out
notification            = never
priority                = 5
getenv                  = False
queue 1
